# Generated by Django 3.1.3 on 2021-10-04 11:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20211004_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='collaborators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('github_link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCollab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', tinymce.models.HTMLField()),
                ('projectimage', models.URLField(max_length=500)),
                ('projectimageurl', models.URLField(max_length=500)),
                ('collabs', models.ManyToManyField(to='about.collaborators')),
                ('platforms', models.ManyToManyField(to='about.platforms')),
                ('tags', models.ManyToManyField(to='about.tags')),
            ],
        ),
    ]
