# Generated by Django 3.1.3 on 2021-10-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_collaborators_projectcollab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcollab',
            old_name='collabs',
            new_name='collaborators',
        ),
    ]
